const jsonobj = {
  _type: "news",
  didUMean: "",
  totalCount: 83,
  relatedSearch: [],
  value: [
    {
      id: "926774669287118787",
      title:
        "Biden pushes to end Afghan evacuation by Aug. 31--but orders backup plan",
      url: "https://www.washingtonpost.com/politics/biden-afghan-evacuation-deadline/2021/08/24/51f8cca0-04e7-11ec-a266-7c7fe02fa374_story.html",
      description:
        "Biden says every additional day would bring more risk to U.S. troops but finishing the evacuation by months end depends on Taliban cooperation. The uncertainty provoked confusion and anger among those worried about evacuees.",
      body: "Comment\n0\nPresident Biden on Tuesday reaffirmed his intent to complete the U.S. evacuation mission in Afghanistan by Aug. 31, but he also ordered contingency plans if that cannot be accomplished  a position that stoked a new round of outrage and confusion about the United States exit from a two-decade war.\narrow-right\nThe result was looming uncertainty over whether the United States would finalize its exit within a week, as Biden wants, as well as intensifying anger from would-be Afghan refugees, U.S. allies worried about getting their own personnel out of the country, and veterans concerned about the fate of those who helped the war effort.\nSpeaking at the White House  after meeting virtually with leaders of the Group of Seven large industrialized democracies, Biden said that the United States was on pace to wrap up its efforts in Afghanistan by Aug. 31 and that any extension risked terrorist attacks.\nAdvertisement\nStory continues below advertisement\nThe sooner we can finish, the better, Biden said. Each day of operations brings added risk to our troops.\nBut the president also said that meeting that deadline would require avoiding unforeseen disruptions and that it depends upon the Taliban continuing to cooperate and allow access to the airport for those who were transporting out. He said that he asked the Pentagon and the State Department to draft contingency plans should the U.S. government have to shift its timeline.\nReflecting the moments extreme delicacy, CIA Director William J. Burns held a secret meetingMonday in Kabul with the Talibans de facto leader, Abdul Ghani Baradar, according to U.S. officials familiar with the matter who spoke on the condition of anonymity to discuss sensitive diplomacy. The White House declined to publicly discuss the decision to dispatch Burns.\nAdvertisement\nStory continues below advertisement\nThe notion of a firm deadline was already drawing sharp criticism Tuesday, even from longtime Biden supporters. We must extend the withdrawal deadline and work with intl partners to ensure ALL allies find safety from the Taliban, tweeted Sen. Jeanne Shaheen (D-N.H.). Arbitrary deadlines & bureaucracy are no excuse for lives lost.\nThe president delivered his remarks on Afghanistan five hours behind schedule and did not take questions from reporters. West Wing officials scrambled to reschedule the days events, underlining how the sharply the crisis in Afghanistan has upended the White Houses daily public relations efforts.\nBidens comments appeared designed to leave some wiggle room amid a volatile situation on the ground in Afghanistan. Yet they did little to quell the frustration of the presidents adversaries and allies, at home and abroad, about his handling of the withdrawal.\nAmericans debate whats right in Afghanistan\nThe United States has already begun reducing its military footprint at the Kabul airport, the gateway for leaving the country. Pentagon spokesman John Kirby said hundreds of troops had left the airport, but he indicated that a full withdrawal of U.S. troops from the facility has not been ordered. More than 5,000 U.S. troops remain, defense officials said, down from a high of about 5,800.\nAdvertisement\nStory continues below advertisement\nAnd evacuations are proceeding apace, Defense Department officials said. Between U.S. military flights and those involving other aircraft, more than 21,000 people were evacuated on Monday alone, Army Maj. Gen. Hank Taylor told reporters at the Pentagon.\nThe Taliban, which recently ousted the U.S.-backed government in Afghanistan repeated Tuesday that it views the Aug. 31 deadline as final The group is still allowing foreign nationals to leave, spokesman Zabiullah Mujahid said, but is barring Afghan nationals from the airport. We are asking the Americans, please change your policy and dont encourage Afghans to leave, he said.\nBiden argued that the delicate arrangement that is allowing a steady stream of evacuations will not last forever.\nStory continues below advertisement\nThus far, the Taliban have been taking steps to work with us so we can get our people out. But its a tenuous situation, he said. Were already had some gunfighting breaking out. We run a serious risk of it breaking down as time goes on.\nAdvertisement\nBiden heard growing notes of dissent and frustration during a brief virtual meeting with leaders of other major industrialized democracies. All the G-7 nations except Japan also are members of NATO, which fought alongside the United States in Afghanistan for two decades. Several of those leaders favored extending the mission, even briefly, to help evacuate more activists, teachers, prominent women and other vulnerable people.\nBritish Prime Minister Boris Johnson is on record seeking more time. Prime Minister Justin Trudeau on Tuesday said Canada is ready to stay in Afghanistan beyond Aug. 31. French President Emmanuel Macron told Biden during a call last week that allies have a moral responsibility to extract vulnerable people.\nStory continues below advertisement\nEuropean Union leaders Charles Michel and Ursula von der Leyen pressed Biden on the timeline at the G-7 session on Tuesday. A lot of leaders, including Ursula and myself, have noted concerns, Michel said after the meeting. Weve got the 31st as a deadline, and we want to know whats going to happen after that.\nAdvertisement\nMeanwhile, a group of legislators from G-7 countries discouraged what they called arbitrary dates for ending military support to the evacuation. They were joined by Sen. Robert Menendez (D-N.J.), chairman of the Senate Foreign Relations Committee.\nAdding their voices were veterans groups, which are focused on Afghan citizens who for years helped American service members as interpreters and in other roles, and who now face possible reprisals from the Taliban.\nStory continues below advertisement\nIf we pull out by August 31st, we are going to leave people who sacrificed their entire lives and their families to protect Americans, said Jake Harriman, a former Marine Corps officer who has been involved in private efforts to rescue Afghans.\nThis excuse that were at the whims of the Taliban is insane, he added.\nPaul Rieckhoff, a veterans advocate who served in the Army, voiced similar frustration.\nAdvertisement\nThe level of anger and betrayal being felt across the veterans community right now is off the charts, he tweeted. Rieckhoff cited an effort launched Monday by dozens of veterans organizations to meet with Biden officials and convey concerns that the United States would pull out before the rescue effort was complete.\nStory continues below advertisement\nIn speaking to the G-7 leaders, Biden did not guarantee the mission would wrap up by monthss end, White House press secretary Psaki said, but rather explained that it would finish when the United States had achieved its objectives.\nBut Psaki was vague about what conditions would trigger the contingency plans Biden has ordered. She said the United States is f",
      snippet:
        "Biden says every additional day would bring more risk to U.S.\ntroops but finishing the evacuation by months end depends on Taliban cooperation.",
      keywords: "",
      language: "en",
      isSafe: true,
      datePublished: "2021-08-24T23:33:05",
      provider: {
        name: "washingtonpost",
        favIcon: "",
        favIconBase64Encoding: "",
      },
      image: {
        url: "https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/UNSY6NAFEII6ZM6EYRRLD3OPZA.jpg&amp;w=1440",
        height: 0,
        width: 0,
        thumbnail: "",
        thumbnailHeight: 0,
        thumbnailWidth: 0,
        base64Encoding: "",
        name: null,
        title: null,
        provider: {
          name: "washingtonpost",
          favIcon: "",
          favIconBase64Encoding: "",
        },
        imageWebSearchUrl: null,
        webpageUrl:
          "https://www.washingtonpost.com/politics/biden-afghan-evacuation-deadline/2021/08/24/51f8cca0-04e7-11ec-a266-7c7fe02fa374_story.html",
      },
    },
    {
      id: "4831847795309154578",
      title: "Afghan families flood lawmakers' offices for help",
      url: "https://www.latimes.com/politics/story/2021-08-25/afghan-families-in-california-flood-lawmakers-offices-for-assistance",
      description:
        "Families of American citizens and Afghans trapped in Kabul have turned to Congress for assistance. But lawmakers say theres only so much they can do.",
      body: "snaked outside\nRep. Eric Swalwells Castro Valley office last week as Afghan Americans sought help from the Democratic congressman to rescue their loved ones in Afghanistan. One family drove up from Utah.\nIts been overwhelming for our staff, but theyre committed to doing all they can, Swalwell (D-Dublin) said Tuesday.\nAfter the Talibans seizure of Kabul last week following the Biden administrations abrupt withdrawal of U.S. troops from Afghanistan, thousands of American citizens and Afghans trapped in the war-torn nation are desperate for U.S. help. Many have turned to Congress for assistance. But lawmakers say theres only so much they can do despite their best efforts.\nThe State Department, which gave all 435 representatives and 100 senators the same email address to contact for constituent help, is ultimately responsible for coordinating evacuations from Afghanistan and has been inundated with thousands of requests. Some lawmakers have turned to volunteer organizations and nonprofit groups for quicker assistance.\nAdvertisement\nSwalwells district is home to a large swath of Californias Afghan American population, whose strong and growing presence in the East Bay has contributed to the regions diversity. The San Francisco Bay Area is home to\nroughly 60,000 Afghan Americans\n the highest concentration in the country.\nSwalwell said his Twitter inbox has been flooded with direct messages from concerned constituents seeking assistance to evacuate their family members. He and his staff members have a text message group in which they share updates about  constituents cases  of which there are over 1,000, he said.\nBoth Swalwell and  Sen. Alex Padilla (D-Calif.) have\ndedicated webpages\nand email addresses to assist individuals seeking to flee Afghanistan.\nRep. Ami Bera (D-Elk Grove) said Tuesday that his office has submitted more than 6,500 names to the State Department. He said other members of Congress have reached out to his office, including a colleague who advocated on behalf of three college students who could not get to the Hamid Karzai International Airport in Kabul to flee the country.\nI talked to my constituent services person. We reached out directly to those three constituents, and they were able to get to the airport and successfully out of the country, Bera said.\nBiden administration officials have said they cannot provide an exact number of Americans still in Afghanistan, but national security advisor Jake Sullivan estimated on Sunday that roughly a few thousand were still trying to leave the country.\nRep. Ro Khanna (D-Fremont) represents one of the largest Afghan ethnic enclaves in the country. Khanna, whose district is home to Little Kabul, has been openly critical of the Biden administrations abrupt withdrawal from Afghanistan.\nHe\nTuesday that his office staff welcomed an Afghan family to Milpitas after they experienced five days of attempting to fly out of Kabul, plus three additional days of international travel.\nAdvertisement\nRep. Scott Peters (D-Coronado) said his district  home to one of the largest veteran populations in the country  has been hit hard by the fallout in Afghanistan.\nWe have been fielding a lot of calls from people who know people on the ground, he said Tuesday. Some of them are veterans who have been very heartbroken by this whole process.\nPeters said the State Department was a little slow to wake up to the severity of the situation in Afghanistan. For that reason, he said, his office is working with volunteer networks and third-party groups such as the Truman Center for National Policy, which is helping evacuate Americans and allies from Afghanistan.\nIm really, really frightened, appalled and embarrassed as an American that this is how this has been executed, he said.",
      snippet:
        "Families of American citizens and Afghans trapped in Kabul have turned to Congress for assistance.\nBut lawmakers say theres only so much they can do.",
      keywords: "",
      language: "en",
      isSafe: true,
      datePublished: "2021-08-25T12:00:24.571",
      provider: { name: "latimes", favIcon: "", favIconBase64Encoding: "" },
      image: {
        url: "https://ca-times.brightspotcdn.com/dims4/default/38a16e0/2147483647/strip/true/crop/5452x2862+0+386/resize/1200x630!/quality/90/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2Fd3%2F32%2F270a1c75412986da2f8b007227ac%2Fhttps-delivery.gettyimages.com%2Fdownloads%2F1232324437",
        height: 0,
        width: 0,
        thumbnail: "",
        thumbnailHeight: 0,
        thumbnailWidth: 0,
        base64Encoding: "",
        name: null,
        title: null,
        provider: { name: "latimes", favIcon: "", favIconBase64Encoding: "" },
        imageWebSearchUrl: null,
        webpageUrl:
          "https://www.latimes.com/politics/story/2021-08-25/afghan-families-in-california-flood-lawmakers-offices-for-assistance",
      },
    },
    {
      id: "6968728828618854609",
      title: "Remembering Rolling Stones drummer Charlie Watts",
      url: "https://www.nbcnews.com/nightly-news/video/remembering-rolling-stones-drummer-charlie-watts-119375429992",
      description:
        "80-year-old Charlie Watts was at the heart of the Rolling Stones for over 50 years. He died today in a London hospital surrounded by family, according to a spokesperson.",
      body: "Remembering Rolling Stones drummer Charlie Watts\n01:19\nShare this -\ncopied\n80-year-old Charlie Watts was at the heart of the Rolling Stones for over 50 years. He died today in a London hospital surrounded by family, according to a spokesperson.\nAug. 24, 2021",
      snippet:
        "80-year-old Charlie Watts was at the heart of the Rolling Stones for over 50 years.\nHe died today in a London hospital surrounded by family, according to a spokesperson.",
      keywords: "",
      language: "en",
      isSafe: true,
      datePublished: "2021-08-24T23:13:19",
      provider: { name: "nbcnews", favIcon: "", favIconBase64Encoding: "" },
      image: {
        url: "https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1200-630,f_auto,q_auto:best/mpx/2704722219/2021_08/1629846762202_nn_sgo_rolling_stones_drummer_charlie_watts_obit_210824_1920x1080-5ejru0.jpg",
        height: 0,
        width: 0,
        thumbnail: "",
        thumbnailHeight: 0,
        thumbnailWidth: 0,
        base64Encoding: "",
        name: null,
        title: null,
        provider: { name: "nbcnews", favIcon: "", favIconBase64Encoding: "" },
        imageWebSearchUrl: null,
        webpageUrl:
          "https://www.nbcnews.com/nightly-news/video/remembering-rolling-stones-drummer-charlie-watts-119375429992",
      },
    },
    {
      id: "2262167649995728139",
      title:
        "Two members of Congress fly to Kabul amid evacuation, stunning State department and military officials",
      url: "https://news.yahoo.com/two-members-congress-fly-kabul-003208089.html",
      description:
        "Officials said Rep. Seth Moulton, D-Mass., and Rep. Peter Meijer, R-Mich., flew in on a charter craft and were at the Kabul airport for several hours.",
      body: "Chaos at Kabul airport raises questions about U.S. evacuation effort\nThe U.S. military found out about the visit as the legislators aircraft was inbound to Kabul according to the officials. The officials spoke on condition of anonymity to discuss ongoing military operations.\nOne senior U.S. official said the administration saw the lawmakers visit as manifestly unhelpful and other officials said the visit was viewed as a distraction for troops and commanders at the airport who are waging a race against time to evacuate thousands of Americans, at-risk Afghans and others as quickly as possible.\nStory continues\nHouse Speaker Nancy Pelosi issued a statement Tuesday evening taking note of the desire of some legislators to visit Afghanistan and saying she was writing to reiterate that the Departments of Defense and State have requested that Members not travel to Afghanistan and the region during this time of danger. Ensuring the safe and timely evacuation of individuals at risk requires the full focus and attention of the U.S. military and diplomatic teams on the ground in Afghanistan.\nThe Pentagon has repeatedly expressed concerns about security threats in Kabul, including by the Islamic State group. When members of Congress have routinely gone to war zones over the past two decades, their visits are typically long planned and coordinated with officials on the ground in order to ensure their safety.\nLatest on Afghanistan:\nBiden says US 'on a pace' for Aug. 31 pullout; Taliban block Afghans from airport\nPresident Joe Biden on Tuesday said he is sticking to his Aug. 31 deadline for completing the risky airlift as people flee Taliban-controlled Afghanistan. He said a key reason for the deadline is the ongoing IS threat targeting the airport. The Islamic State groups Afghanistan affiliate is known for staging suicide attacks on civilians.\nThe two congressmen said they went into their visit wanting to push the president to extend the August 31st deadline. After talking with commanders on the ground and seeing the situation here, it is obvious that because we started the evacuation so late, that no matter what we do, we wont get everyone out on time, even by September 11.\nThis article originally appeared on USA TODAY:\nOur goal is to create a safe and engaging place for users to connect over interests and passions. In order to improve our community experience, we are temporarily suspending article commenting\nRecommended Stories\n2 Congress members fly to Kabul amid chaotic evacuation\nTwo members of Congress flew unannounced into Kabul airport in the middle of the ongoing chaotic evacuation Tuesday, stunning State Department and U.S. military personnel who had to divert resources to provide security and information to the lawmakers, U.S. officials said.  Rep. Seth Moulton, D-Mass., and Rep. Peter Meijer, R-Mich., flew in and out on charter aircraft and were on the ground at the Kabul airport for several hours.  As Members of Congress, we have a duty to provide oversight on the executive branch,' the two said in their statement.\n2h ago\nUS increases Kabul evacuations as threats persist\nThe U.S. military had its biggest day of evacuation flights out of Taliban-held Afghanistan, flying more than 10,000 people to safety in 24 hours, but deadly violence is still blocking many desperate evacuees from getting to Kabul's airport. (Aug. 23)\n1d ago",
      snippet: "Officials said Rep.\nSeth Moulton, D-Mass., and Rep.",
      keywords: "",
      language: "en",
      isSafe: true,
      datePublished: "2021-08-25T00:47:37",
      provider: { name: "yahoo", favIcon: "", favIconBase64Encoding: "" },
      image: {
        url: "https://s.yimg.com/ny/api/res/1.2/YA8VjKjslVuRkEk3dxok1w--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD05NzE-/https://s.yimg.com/uu/api/res/1.2/VF8lT05clW0ChpGCiZ6OWw--~B/aD0yOTEzO3c9MzYwMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/usa_today_news_641/2ebf016afe8bfdb47a844039708bcd12",
        height: 0,
        width: 0,
        thumbnail: "",
        thumbnailHeight: 0,
        thumbnailWidth: 0,
        base64Encoding: "",
        name: null,
        title: null,
        provider: { name: "yahoo", favIcon: "", favIconBase64Encoding: "" },
        imageWebSearchUrl: null,
        webpageUrl:
          "https://news.yahoo.com/two-members-congress-fly-kabul-003208089.html",
      },
    },
    {
      id: "4466371020735959250",
      title:
        "'Keep your guard up': CDC studies show waning COVID vaccine efficacy as delta variant sweeps US",
      url: "https://news.yahoo.com/keep-guard-cdc-studies-show-004421531.html",
      description:
        "Unvaccinated people in Los Angeles were more than 29 times more likely to be hospitalized than the vaccinated, according to a CDC study.",
      body: "FDA approves of first COVID-19 vaccine\nThe research comes as the FDA has given its full approval of the Pfizer-BioNTech COVID-19 vaccine, and soon after the agency and the CDC recommended a third vaccine dose to those who have compromised immune systems. A booster shot is expected to be available to fully vaccinated Americans who got their second dose at least eight months prior beginning Sept. 20, according to the White House.\nStory continues\nThats too long to wait, Topol said. Based on the research, Topol said immunity may begin to go down at around the five- or six-month mark, leaving vaccinated people more vulnerable to infection.\nJustin Bishop, 13, receives the first dose of the Pfizer-BioNTech COVID-19 vaccine on May 14, 2021, at the Mount Sinai South Nassau Vaxmobile in Freeport, N.Y.\n\"If you wait until eight months, youre two or three months vulnerable while delta is circulating. Whatever youre doing in life, unless you live in a cave, you're getting incremental exposures,\" Topol said.\nThe study among health care personnel and other frontline workers was conducted in eight locations across six states beginning in December 2020 and ending Aug. 14. The research shows vaccine effectiveness was 91% before the dominance of the delta variant, and it has since dropped to 66%.\nTopol said he doesnt believe the decline in effectiveness can be solely attributed to waning immunity over time, but has a lot to do with the delta variants contagious nature. Other factors, such as laxed mitigation measures  relaxation of masking and distancing  could contribute, but are harder to quantify.\nNo, a vaccine doesn't make you 'Superman':\nBreakthrough COVID-19 cases are increasing amid delta variant.\nAlthough these interim findings suggest a moderate reduction in the effectiveness of COVID-19 vaccines in preventing infection, the sustained two thirds reduction in infection risk underscores the continued importance and benefits of COVID-19 vaccination, the CDC said.\nTopol said the research underscores the need for vaccines for all, but also the need to protect vaccinated people. The delta wave will pass eventually, but even those who are fully vaccinated need to keep your guard up, he said.\nWere not getting the word out enough that people who have been vaccinated are not protected as much as they think. They need to mask up, they need to do everything they can. Make believe that there wasn't a vaccine,\" he said.\nThis article originally appeared on USA TODAY:\nOur goal is to create a safe and engaging place for users to connect over interests and passions. In order to improve our community experience, we are temporarily suspending article commenting\nRecommended Stories\nINSIDER\nJennifer Boeder told Insider she believes her friend is sharing dangerous disinformation that's not in touch with reality.\n5h ago",
      snippet:
        "Unvaccinated people in Los Angeles were more than 29 times more likely to be hospitalized than the vaccinated, according to a CDC study.\nFDA approves of first COVID-19 vaccine.",
      keywords: "",
      language: "en",
      isSafe: true,
      datePublished: "2021-08-25T00:44:21",
      provider: { name: "yahoo", favIcon: "", favIconBase64Encoding: "" },
      image: {
        url: "https://s.yimg.com/ny/api/res/1.2/3Dq_bS6HmzE_8GZBKD3kNg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://s.yimg.com/uu/api/res/1.2/.aFqFlMowULsSUppHFA8yQ--~B/aD00MDAwO3c9NjAwMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/usa_today_news_641/eaa0974a44243493575fb56a3b1b50c1",
        height: 0,
        width: 0,
        thumbnail: "",
        thumbnailHeight: 0,
        thumbnailWidth: 0,
        base64Encoding: "",
        name: null,
        title: null,
        provider: { name: "yahoo", favIcon: "", favIconBase64Encoding: "" },
        imageWebSearchUrl: null,
        webpageUrl:
          "https://news.yahoo.com/keep-guard-cdc-studies-show-004421531.html",
      },
    },
    {
      id: "1216465393997879945",
      title:
        "House passes John Lewis voting rights bill, sends measure to Senate for tougher fight",
      url: "https://www.nbcnews.com/politics/politics-news/house-passes-john-lewis-voting-rights-bill-sends-measure-senate-n1277566",
      description:
        "House Democrats passed a sweeping voting rights bill named after late civil rights icon Rep. John Lewis, D-Ga., on Tuesday.",
      body: "House Democrats passed a sweeping voting rights bill named after late civil rights icon Rep. John Lewis, D-Ga., on Tuesday.\n\nThe John Lewis Voting Rights Advancement Act was approved 219-212. All Republicans voted against the legislation.\n\nThe voting bill is part of a broader goal of congressional Democrats to strengthen voting laws at the federal level to fight back against restrictive voting laws passed in GOP-led states, such as Texas and Georgia. However, the bill faces steep opposition in the Senate, where Democrats hold a wafer-thin majority.\n\nThis week, the House returned from its recess to take up the bipartisan infrastructure bill and a resolution for Democrats' $3.5 trillion budget package, which includes funding for much of President Joe Biden's legislative agenda. The procedural motion used to pass the trillion-dollar resolution paved the way for the House to vote on the voting rights bill, which was re-introduced last week by Rep. Terri Sewell, D-Ala.\n\nThe legislation would require states with a recent history of discrimination to receive federal \"preclearance\" to make changes to their voting laws, which directly addresses the U.S. Supreme Courts 2013 ruling in Shelby County v. Holder. That ruling gutted the preclearance system of the Voting Rights Act of 1965, which civil rights advocates argue was successful in blocking proposed voting restrictions in states and localities with a history of racial discrimination.\n\nLast week, House Speaker Nancy Pelosi, D-Calif., said in a statement that Congress had not only an ironclad Constitutional mandate, but a moral responsibility to pass the bill.\n\nHowever, this is not the first time House Democrats have tackled election law. In March, House Democrats passed the For the People Act, a sweeping bill that seeks to change campaign finance, voting and ethics laws.\n\nThat bill would expand access to the ballot box by creating automatic voter registration across the country by registering eligible voters whenever they interact with a government agency, restoring the voting rights of the formerly incarcerated, expanding early voting and modernizing America's voting systems.\n\nHowever, Senate Republicans filibustered the voting rights legislation in June and the vote to advance an amended version of the \"For The People Act\" split along party lines 50-50, short of the 60 needed. All Democrats voted to begin debate and Republicans unanimously voting to block the bill.\n\nThe passage of the voting measure was the final vote of the week for the House. Members depart Washington and won't return until September 20.",
      snippet:
        "House Democrats passed a sweeping voting rights bill named after late civil rights icon Rep.\nJohn Lewis, D-Ga., on Tuesday.",
      keywords: "",
      language: "en",
      isSafe: true,
      datePublished: "2021-08-24T23:31:00",
      provider: { name: "nbcnews", favIcon: "", favIconBase64Encoding: "" },
      image: {
        url: "https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1500w,f_auto,q_auto:best/newscms/2021_34/3501337/210824-voting-right-act-ew-648p.jpg",
        height: 0,
        width: 0,
        thumbnail: "",
        thumbnailHeight: 0,
        thumbnailWidth: 0,
        base64Encoding: "",
        name: null,
        title: null,
        provider: { name: "nbcnews", favIcon: "", favIconBase64Encoding: "" },
        imageWebSearchUrl: null,
        webpageUrl:
          "https://www.nbcnews.com/politics/politics-news/house-passes-john-lewis-voting-rights-bill-sends-measure-senate-n1277566",
      },
    },
    {
      id: "2308739526346950072",
      title: "Kanye West asks court to legally change his name to Ye",
      url: "https://www.nbcnews.com/news/us-news/kanye-west-asks-court-legally-change-his-name-ye-n1277580",
      description:
        "Kanye West filed court documents Tuesday to legally change his name to Ye.",
      body: "LOS ANGELES  Kanye just wants to be Ye.\n\nKanye West filed court documents Tuesday to legally change his name.\n\nThe Los Angeles Superior Court filing says the 44-year-old wants to get rid of his full name  Kanye Omari West  in favor of just his longtime two-letter nickname, Ye, with no middle name or last name.\n\nThe documents, dated Aug. 11 but not sent into the court system until Tuesday, cite personal reasons for the change. An email seeking comment from the attorney who filed the documents was not immediately returned.\n\nA judge must approve of the change before it becomes official.\n\nWest, who has called himself Ye on his social media pages for years, tweeted that he wanted the change in 2018, saying, the being formally known as Kanye West. I am YE.\n\nThe moniker was also the title of his 2018 album. He has said in interviews that, along with being a shortening of his first name he likes, that its a word used throughout the Bible.\n\nWest is in the middle of a divorce with Kim Kardashian West, who did not ask that her last name be changed back to just Kardashian when she filed to split from him in February. The couples four children also have his last name.\n\nHe has been holding a series of stadium listening parties for his forthcoming 10th studio album Donda, which is scheduled to be released before the end of August.",
      snippet:
        "Kanye West filed court documents Tuesday to legally change his name to Ye.\nLOS ANGELES  Kanye just wants to be Ye.",
      keywords: "",
      language: "en",
      isSafe: true,
      datePublished: "2021-08-25T10:52:55",
      provider: { name: "nbcnews", favIcon: "", favIconBase64Encoding: "" },
      image: {
        url: "https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1500w,f_auto,q_auto:best/newscms/2021_34/3501395/210824-kanye-west-mc-1132.JPG",
        height: 0,
        width: 0,
        thumbnail: "",
        thumbnailHeight: 0,
        thumbnailWidth: 0,
        base64Encoding: "",
        name: null,
        title: null,
        provider: { name: "nbcnews", favIcon: "", favIconBase64Encoding: "" },
        imageWebSearchUrl: null,
        webpageUrl:
          "https://www.nbcnews.com/news/us-news/kanye-west-asks-court-legally-change-his-name-ye-n1277580",
      },
    },
    {
      id: "1002056134487568891",
      title:
        "Supreme Court declines Biden administration's efforts to end 'Remain in Mexico' policy",
      url: "https://www.nbcnews.com/politics/supreme-court/supreme-court-declines-biden-administration-s-efforts-end-remain-mexico-n1277572",
      description:
        "The Supreme Court on Tuesday denied the Biden administrations request to pause the implementation of a Trump-era immigration policy.",
      body: 'The Supreme Court on Tuesday denied the Biden administrations request to pause the implementation of a Trump-era immigration policy.\n\nThe Justice Department had asked the court late last week to delay the reinstatement of the policy, known as Remain in Mexico," arguing in its brief that the policy had been dormant for more than a year and that abruptly reinstating it would prejudice the United States relations with vital regional partners, severely disrupt its operations at the southern border, and threaten to create a diplomatic and humanitarian crisis.\n\nA lower court had ordered the reinstatement of the program, forcing the administration to appeal to the Supreme Court.\n\nThe policy was meant to discourage asylum-seekers but critics argue that it denies people the legal right to seek protection in the U.S. and forced them to wait in dangerous Mexican border cities. It requires asylum seekers to remain in Mexico until their court date in the U.S. and previously left tens of thousands of Central American migrants waiting in tent cities in places like Matamoros, Mexico, where they were often subjected to robbery, kidnapping and assault.\n\nPresident Joe Biden also suspended the policy on his first day in office. In addition, in June, the Department of Homeland Security announced that it was permanently terminating the program.\n\nThe Trump administration largely stopped using the Remain in Mexico policy at the onset of the pandemic because of the issuance of a public health order that allowed the U.S. to turn back virtually everyone crossing the Southwest border. That public health order remains in effect.\n\nAttorneys general in Missouri and Texas sued the Biden administration to reinstate the policy, claiming the high number of asylum seekers was burdening states without DHS being able to detain them. Texas and Missouri also argued that the Biden administration had not gone through proper administrative procedures in ending the policy.\n\nThe Biden administration had appealed to the Supreme Court for an emergency stay on the order, but Tuesday night the Supreme Court denied the stay because, The applicants have failed to show a likelihood of success that they would win their claim to rescind the policy.\n\nIn a statement, DHS said it "will comply with the order in good faith."\n\n"DHS remains committed to building a safe, orderly, and humane immigration system that upholds our laws and values," the agency said in a statement.\n\nOmar Jadwat, director of the ACLUs Immigrants Rights Project, called on lawmakers and the White House to end the program.\n\nThe Biden administration was correct to rescind the Trump return to Mexico policy, the whole point of which was to punish people for seeking asylum by trapping them in miserable and dangerous conditions. The government must take all steps available to fully end this illegal program, including by re-terminating it with a fuller explanation. What it must not do is use this decision as cover for abandoning its commitment to restore a fair asylum system.\n\nPaola Luisi, director of Families Belong Together, a coalition of more than 250 advocacy organizations, also pressed the Biden administration to end the program.\n\nWe cannot accept any policy  even temporary  that separates families. We urge the Biden administration to do everything within their means to put an end to this cruel Remain in Mexico policy once and for all," Luisi said in a statement.',
      snippet:
        "The Supreme Court on Tuesday denied the Biden administrations request to pause the implementation of a Trump-era immigration policy.\nThe Supreme Court on Tuesday denied the Biden administrations request to pause the implementation of a Trump-era immigration policy.",
      keywords: "",
      language: "en",
      isSafe: true,
      datePublished: "2021-08-25T01:49:38",
      provider: { name: "nbcnews", favIcon: "", favIconBase64Encoding: "" },
      image: {
        url: "https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1500w,f_auto,q_auto:best/newscms/2021_34/3484912/210621-supreme-court-al-0802.jpg",
        height: 0,
        width: 0,
        thumbnail: "",
        thumbnailHeight: 0,
        thumbnailWidth: 0,
        base64Encoding: "",
        name: null,
        title: null,
        provider: { name: "nbcnews", favIcon: "", favIconBase64Encoding: "" },
        imageWebSearchUrl: null,
        webpageUrl:
          "https://www.nbcnews.com/politics/supreme-court/supreme-court-declines-biden-administration-s-efforts-end-remain-mexico-n1277572",
      },
    },
    {
      id: "2265507054188517466",
      title: "Serena Williams pulls out of U.S. Open due to injury",
      url: "https://www.nbcnews.com/news/sports/serena-williams-pulls-out-u-s-open-due-injury-n1277590",
      description:
        "Serena Williams will not play in the U.S. Open because of an injury.",
      body: 'Serena Williams will not play in the U.S. Open because of an injury, she said Wednesday.\n\n"After careful consideration and following the advice of my doctors and medical team, I have decided to withdraw from the US Open to allow my body to heal completely from a torn hamstring," Williams told her 13.5 million followers on Instagram.\n\n"New York is one of the most exciting cities in the world and one of my favorite places to play  I\'ll miss seeing the fans but will be cheering everyone on from afar," Williams added. "Thank you for your continued support and love. I\'ll see you soon."\n\nWilliams, 39, stopped playing her first-round match at Wimbledon in June during the first set after she slipped on the grass court during a point and hurt her leg. She did not compete in the Olympics in Tokyo.\n\nWith 23 Grand Slam singles titles, Williams holds the record for the most of any female player in the open era. She has won six of those titles at the U.S. Open.\n\nShe is not the first tennis star to withdraw from the tournament. Rafael Nadal, 35, and Roger Federer, 40, both ended their seasons when they pulled out of the U.S. Open earlier this month. Nadal, Federer and Novak Djokovic are all tied with 20 Grand Slam titles.\n\nNadal withdrew due to chronic foot pain due to an old injury, while Federer has undergone four knee surgeries.\n\nThis is the first year since 1997 that the U.S. Open will be held without Federer, Nadal and Williams playing for singles titles.\n\nThe U.S. Open is set to begin Monday and will run through Sept. 12 in Queens.',
      snippet:
        "Serena Williams will not play in the U.S.\nOpen because of an injury.",
      keywords: "",
      language: "en",
      isSafe: true,
      datePublished: "2021-08-25T13:05:00",
      provider: { name: "nbcnews", favIcon: "", favIconBase64Encoding: "" },
      image: {
        url: "https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1500w,f_auto,q_auto:best/newscms/2021_34/3501448/210825-serena-williams-jm-0943.jpg",
        height: 0,
        width: 0,
        thumbnail: "",
        thumbnailHeight: 0,
        thumbnailWidth: 0,
        base64Encoding: "",
        name: null,
        title: null,
        provider: { name: "nbcnews", favIcon: "", favIconBase64Encoding: "" },
        imageWebSearchUrl: null,
        webpageUrl:
          "https://www.nbcnews.com/news/sports/serena-williams-pulls-out-u-s-open-due-injury-n1277590",
      },
    },
    {
      id: "7789131200740919102",
      title:
        "Granderson: The election is over. In Arizona, the Trump campaign continues",
      url: "https://www.latimes.com/opinion/story/2021-08-25/2020-election-is-over-but-in-arizona-the-trump-campaign-continues",
      description:
        "Democracy is being poisoned by people who care only about winning.",
      body: "I would like to share with you a brief conversation about politics that I didnt want to have. But the man in the Arizona bar sitting a couple of stools down from me was persistent, so I reluctantly engaged. He first brought up President Bidens handling of Afghanistan, specifically the idiocy  his word, not mine  of making a deal with the Taliban in the first place. When I pointed out that it was the former president and not the current one who negotiated the deal  going so far as to pull up video of Donald Trump bragging about making the deal  the man pivoted to Hillary Clintons email. The Fox News buzzwords just kept coming. It was like playing a drinking game at Tucker Carlsons house. The best part was when he said the electoral college had to be protected so that California and New York dont ruin our democracy. I asked how a system saves democracy when it allows the candidate with fewer votes to claim victory? He paused for a moment. Then went back to Clintons emails. But, hey, at least he paused. Thats more than can be said about Republicans in the Arizona state Senate, who in their rush to show their undying allegiance to Trumpism are turning democracy into roadkill. It has been more than nine months since the 2020 general election, and some of these bullheaded elected officials are still having a hard time believing that their president  who at no point received even a 50% approval rating  could lose his reelection bid. So instead of accepting the election results, accepting the findings from the Maricopa County sample ballot recount, or accepting findings of two firms accredited by the federal U.S. Election Assistance Commission, the Republican-controlled state senate went all in on the big lie. Adding to the insanity, Cyber Ninjas, the company they hired to conduct their audit, had no experience auditing election results before and is led by a Trump supporter who has repeated wild conspiracy theories about election fraud. The combination of toxic partisanship and misinformation is being used as a fundraiser for Trump supporters seeking office, like state Rep. Mark Finchem, who earlier this month announced he is running for Arizona secretary of state. Weve already shown evidence of fraud  now its time for them to prove it wasnt, he tweeted, with a picture of a MAGA red T-shirt that read #ProveIt. One Scottsdale resident told the Wall Street Journal that she believes the Cyber Ninja audit will prove Trump won Arizona and that there will be a soft coup and we will have President Trump reinstalled. A soft coup. I would hate to see her sitting a couple of bar stools down from me. The results of this problematic audit? Delayed because three members of the five-person audit team tested positive for COVID-19. Thats on brand for a state party that censured the governor for enacting emergency orders to stop the spread of the virus. When the state GOP chair, Kelli Ward, told the Associated Press that she will always put America first, I wondered if she understood what that would mean. Because up to this point, it appears she is putting Trumpism first, and democracy is suffering because of it. Without democracy, there is no America. At least not the version we used to justify invading Iraq to end the dictatorial rule of Saddam Hussein in 2003. Not the version of America we used to justify staying in Afghanistan 10 years after the U.S. Navy SEALs shot and killed Osama bin Laden in a compound in Pakistan. Twenty years of war guided by the premise we were promoting democracy. You would think at a certain point Republicans would see the damage being done to the country they say they love. Instead lawmakers from neighboring Utah, the Midwest and Tennessee have traveled to Arizona to see if they can conduct similar audits back home. Democracy is being poisoned by people who care only about winning. And now theres a retiree in Scottsdale casually talking to the media about participating in a soft coup because her party has led her to believe thats how you handle election results you dont like. Presumably thats better than the attempted hard coup at the U.S. Capitol on Jan. 6. So much trust in our election system is being undermined even though not a single court or state official found evidence of widespread voter fraud. Not that facts matter. If they did, Arizona Republicans would have never gone down this road to begin with. And democracy would not have to look over its shoulder. @LZGranderson",
      snippet:
        "Democracy is being poisoned by people who care only about winning.\nI would like to share with you a brief conversation about politics that I didnt want to have.",
      keywords: "",
      language: "en",
      isSafe: true,
      datePublished: "2021-08-25T10:00:37",
      provider: { name: "latimes", favIcon: "", favIconBase64Encoding: "" },
      image: {
        url: "https://ca-times.brightspotcdn.com/dims4/default/f0255b6/2147483647/strip/true/crop/4706x2471+0+333/resize/1200x630!/quality/90/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2Fca%2Fed%2F935148474c128f84cf9dc7f6e6a9%2Fcampaign-2016-trump.JPEG",
        height: 0,
        width: 0,
        thumbnail: "",
        thumbnailHeight: 0,
        thumbnailWidth: 0,
        base64Encoding: "",
        name: null,
        title: null,
        provider: { name: "latimes", favIcon: "", favIconBase64Encoding: "" },
        imageWebSearchUrl: null,
        webpageUrl:
          "https://www.latimes.com/opinion/story/2021-08-25/2020-election-is-over-but-in-arizona-the-trump-campaign-continues",
      },
    },
  ],
};

export default jsonobj;
